
// --- STUDENT DATA ---
export const students = [
  {
    id: "STD101",
    name: "Alex Jones",
    guardian: "Sarah Jones",
    password: "alex_password",
    dashboard: "https://www.pdf2go.com/assets/blog/how_to_convert_jpg_to_pdf.jpg"
},
{
    id: "STD102",
    name: "Maria Garcia",
    guardian: "Carlos Garcia",
    password: "maria_password",
    dashboard: "https://www.pdf2go.com/assets/blog/how_to_convert_jpg_to_pdf.jpg"
  },
];

// --- TRACKER DATA ---
export const trackerData = {};
export const trackerData2 = {
  "STD101": [
      {
          "Curve ID": "CUR101",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "27/10/2025",
          "Repetition No.": 1,
          "Repetition Name": "\ud83e\udde0 Learn Concept",
          "Repetition Effort": "100%",
          "Session ID": "aaa5e1d6",
          "Session Date": "27/10/2025",
          "Subject Name": "MATHS",
          "Subject ID": "SUB227",
          "Topics Covered": "Arithmetic of parts (introduction), Basic division",
          "File Name(s)": "",
          "File Link(s)": ""
      },
      {
          "Curve ID": "CUR102",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "28/10/2025",
          "Repetition No.": 1,
          "Repetition Name": "\ud83e\udde0 Learn Concept",
          "Repetition Effort": "100%",
          "Session ID": "6f03840d",
          "Session Date": "28/10/2025",
          "Subject Name": "Social",
          "Subject ID": "SUB227",
          "Topics Covered": "Arithmetic of parts (addition of fraction)",
          "File Name(s)": "",
          "File Link(s)": ""
      },
      {
          "Curve ID": "CUR103",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "29/10/2025",
          "Repetition No.": 1,
          "Repetition Name": "\ud83e\udde0 Learn Concept",
          "Repetition Effort": "100%",
          "Session ID": "5e3ddf92",
          "Session Date": "29/10/2025",
          "Subject Name": "MATHS",
          "Subject ID": "SUB227",
          "Topics Covered": "Substraction of fraction",
          "File Name(s)": "",
          "File Link(s)": ""
      },
      {
          "Curve ID": "CUR104",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "31/10/2025",
          "Repetition No.": 1,
          "Repetition Name": "\ud83e\udde0 Learn Concept",
          "Repetition Effort": "100%",
          "Session ID": "19b421ce",
          "Session Date": "31/10/2025",
          "Subject Name": "MATHS",
          "Subject ID": "SUB227",
          "Topics Covered": "Decimal forms, Decimal places, Decimal fraction",
          "File Name(s)": "Decimal fraction, Decimal fraction",
          "File Link(s)": "https://drive.google.com/open?id=15eberZOt6dg4JDBASu9dnwin44hLYTCQ, https://drive.google.com/open?id=15eberZOt6dg4JDBASu9dnwin44hLYTCQ"
      },
      {
          "Curve ID": "CUR106",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "28/10/2025",
          "Repetition No.": 2,
          "Repetition Name": "\ud83d\udd01 Active Recall",
          "Repetition Effort": "60\u201370%",
          "Session ID": "aaa5e1d6",
          "Session Date": "27/10/2025",
          "Subject Name": "Social",
          "Subject ID": "SUB227",
          "Topics Covered": "Arithmetic of parts (introduction), Basic division",
          "File Name(s)": "",
          "File Link(s)": ""
      },
      {
          "Curve ID": "CUR107",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "29/10/2025",
          "Repetition No.": 2,
          "Repetition Name": "\ud83d\udd01 Active Recall",
          "Repetition Effort": "60\u201370%",
          "Session ID": "6f03840d",
          "Session Date": "28/10/2025",
          "Subject Name": "MATHS",
          "Subject ID": "SUB227",
          "Topics Covered": "Arithmetic of parts (addition of fraction)",
          "File Name(s)": "",
          "File Link(s)": ""
      },
      {
          "Curve ID": "CUR108",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "30/10/2025",
          "Repetition No.": 2,
          "Repetition Name": "\ud83d\udd01 Active Recall",
          "Repetition Effort": "60\u201370%",
          "Session ID": "5e3ddf92",
          "Session Date": "29/10/2025",
          "Subject Name": "MATHS",
          "Subject ID": "SUB227",
          "Topics Covered": "Substraction of fraction",
          "File Name(s)": "",
          "File Link(s)": ""
      },
      {
          "Curve ID": "CUR109",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "01/11/2025",
          "Repetition No.": 2,
          "Repetition Name": "\ud83d\udd01 Active Recall",
          "Repetition Effort": "60\u201370%",
          "Session ID": "19b421ce",
          "Session Date": "31/10/2025",
          "Subject Name": "Social",
          "Subject ID": "SUB227",
          "Topics Covered": "Decimal forms, Decimal places, Decimal fraction",
          "File Name(s)": "Decimal fraction, Decimal fraction",
          "File Link(s)": "https://drive.google.com/open?id=15eberZOt6dg4JDBASu9dnwin44hLYTCQ, https://drive.google.com/open?id=15eberZOt6dg4JDBASu9dnwin44hLYTCQ"
      },
      {
          "Curve ID": "CUR111",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "30/10/2025",
          "Repetition No.": 3,
          "Repetition Name": "\ud83e\udde9 Fix Gaps",
          "Repetition Effort": "40\u201350%",
          "Session ID": "aaa5e1d6",
          "Session Date": "27/10/2025",
          "Subject Name": "MATHS",
          "Subject ID": "SUB227",
          "Topics Covered": "Arithmetic of parts (introduction), Basic division",
          "File Name(s)": "",
          "File Link(s)": ""
      },
      {
          "Curve ID": "CUR112",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "31/10/2025",
          "Repetition No.": 3,
          "Repetition Name": "\ud83e\udde9 Fix Gaps",
          "Repetition Effort": "40\u201350%",
          "Session ID": "6f03840d",
          "Session Date": "28/10/2025",
          "Subject Name": "MATHS",
          "Subject ID": "SUB227",
          "Topics Covered": "Arithmetic of parts (addition of fraction)",
          "File Name(s)": "",
          "File Link(s)": ""
      },
      {
          "Curve ID": "CUR113",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "01/11/2025",
          "Repetition No.": 3,
          "Repetition Name": "\ud83e\udde9 Fix Gaps",
          "Repetition Effort": "40\u201350%",
          "Session ID": "5e3ddf92",
          "Session Date": "29/10/2025",
          "Subject Name": "Social",
          "Subject ID": "SUB227",
          "Topics Covered": "Substraction of fraction",
          "File Name(s)": "",
          "File Link(s)": ""
      },
      {
          "Curve ID": "CUR114",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "03/11/2025",
          "Repetition No.": 3,
          "Repetition Name": "\ud83e\udde9 Fix Gaps",
          "Repetition Effort": "40\u201350%",
          "Session ID": "19b421ce",
          "Session Date": "31/10/2025",
          "Subject Name": "MATHS",
          "Subject ID": "SUB227",
          "Topics Covered": "Decimal forms, Decimal places, Decimal fraction",
          "File Name(s)": "Decimal fraction, Decimal fraction",
          "File Link(s)": "https://drive.google.com/open?id=15eberZOt6dg4JDBASu9dnwin44hLYTCQ, https://drive.google.com/open?id=15eberZOt6dg4JDBASu9dnwin44hLYTCQ"
      },
      {
          "Curve ID": "CUR116",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "03/11/2025",
          "Repetition No.": 4,
          "Repetition Name": "\u26a1 Quick Review",
          "Repetition Effort": "20\u201330%",
          "Session ID": "aaa5e1d6",
          "Session Date": "27/10/2025",
          "Subject Name": "MATHS",
          "Subject ID": "SUB227",
          "Topics Covered": "Arithmetic of parts (introduction), Basic division",
          "File Name(s)": "",
          "File Link(s)": ""
      },
      {
          "Curve ID": "CUR117",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "04/11/2025",
          "Repetition No.": 4,
          "Repetition Name": "\u26a1 Quick Review",
          "Repetition Effort": "20\u201330%",
          "Session ID": "6f03840d",
          "Session Date": "28/10/2025",
          "Subject Name": "MATHS",
          "Subject ID": "SUB227",
          "Topics Covered": "Arithmetic of parts (addition of fraction)",
          "File Name(s)": "",
          "File Link(s)": ""
      },
      {
          "Curve ID": "CUR118",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "05/11/2025",
          "Repetition No.": 4,
          "Repetition Name": "\u26a1 Quick Review",
          "Repetition Effort": "20\u201330%",
          "Session ID": "5e3ddf92",
          "Session Date": "29/10/2025",
          "Subject Name": "Social",
          "Subject ID": "SUB227",
          "Topics Covered": "Substraction of fraction",
          "File Name(s)": "",
          "File Link(s)": ""
      },
      {
          "Curve ID": "CUR119",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "07/11/2025",
          "Repetition No.": 4,
          "Repetition Name": "\u26a1 Quick Review",
          "Repetition Effort": "20\u201330%",
          "Session ID": "19b421ce",
          "Session Date": "31/10/2025",
          "Subject Name": "MATHS",
          "Subject ID": "SUB227",
          "Topics Covered": "Decimal forms, Decimal places, Decimal fraction",
          "File Name(s)": "Decimal fraction, Decimal fraction",
          "File Link(s)": "https://drive.google.com/open?id=15eberZOt6dg4JDBASu9dnwin44hLYTCQ, https://drive.google.com/open?id=15eberZOt6dg4JDBASu9dnwin44hLYTCQ"
      },
      {
          "Curve ID": "CUR121",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "10/11/2025",
          "Repetition No.": 5,
          "Repetition Name": "\ud83c\udfaf Final Boost",
          "Repetition Effort": "10\u201315%",
          "Session ID": "aaa5e1d6",
          "Session Date": "27/10/2025",
          "Subject Name": "MATHS",
          "Subject ID": "SUB227",
          "Topics Covered": "Arithmetic of parts (introduction), Basic division",
          "File Name(s)": "",
          "File Link(s)": ""
      },
      {
          "Curve ID": "CUR122",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "11/11/2025",
          "Repetition No.": 5,
          "Repetition Name": "\ud83c\udfaf Final Boost",
          "Repetition Effort": "10\u201315%",
          "Session ID": "6f03840d",
          "Session Date": "28/10/2025",
          "Subject Name": "Social",
          "Subject ID": "SUB227",
          "Topics Covered": "Arithmetic of parts (addition of fraction)",
          "File Name(s)": "",
          "File Link(s)": ""
      },
      {
          "Curve ID": "CUR123",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "12/11/2025",
          "Repetition No.": 5,
          "Repetition Name": "\ud83c\udfaf Final Boost",
          "Repetition Effort": "10\u201315%",
          "Session ID": "5e3ddf92",
          "Session Date": "29/10/2025",
          "Subject Name": "MATHS",
          "Subject ID": "SUB227",
          "Topics Covered": "Substraction of fraction",
          "File Name(s)": "",
          "File Link(s)": ""
      },
      {
          "Curve ID": "CUR124",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "14/11/2025",
          "Repetition No.": 5,
          "Repetition Name": "\ud83c\udfaf Final Boost",
          "Repetition Effort": "10\u201315%",
          "Session ID": "19b421ce",
          "Session Date": "31/10/2025",
          "Subject Name": "MATHS",
          "Subject ID": "SUB227",
          "Topics Covered": "Decimal forms, Decimal places, Decimal fraction",
          "File Name(s)": "Decimal fraction, Decimal fraction",
          "File Link(s)": "https://drive.google.com/open?id=15eberZOt6dg4JDBASu9dnwin44hLYTCQ, https://drive.google.com/open?id=15eberZOt6dg4JDBASu9dnwin44hLYTCQ"
      },
      {
          "Curve ID": "CUR126",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "26/11/2025",
          "Repetition No.": 6,
          "Repetition Name": "\ud83d\udd12 Long-Term Lock",
          "Repetition Effort": "5\u201310%",
          "Session ID": "aaa5e1d6",
          "Session Date": "27/10/2025",
          "Subject Name": "Social",
          "Subject ID": "SUB227",
          "Topics Covered": "Arithmetic of parts (introduction), Basic division",
          "File Name(s)": "",
          "File Link(s)": ""
      },
      {
          "Curve ID": "CUR127",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "27/11/2025",
          "Repetition No.": 6,
          "Repetition Name": "\ud83d\udd12 Long-Term Lock",
          "Repetition Effort": "5\u201310%",
          "Session ID": "6f03840d",
          "Session Date": "28/10/2025",
          "Subject Name": "MATHS",
          "Subject ID": "SUB227",
          "Topics Covered": "Arithmetic of parts (addition of fraction)",
          "File Name(s)": "",
          "File Link(s)": ""
      },
      {
          "Curve ID": "CUR128",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "28/11/2025",
          "Repetition No.": 6,
          "Repetition Name": "\ud83d\udd12 Long-Term Lock",
          "Repetition Effort": "5\u201310%",
          "Session ID": "5e3ddf92",
          "Session Date": "29/10/2025",
          "Subject Name": "MATHS",
          "Subject ID": "SUB227",
          "Topics Covered": "Substraction of fraction",
          "File Name(s)": "",
          "File Link(s)": ""
      },
      {
          "Curve ID": "CUR129",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "30/11/2025",
          "Repetition No.": 6,
          "Repetition Name": "\ud83d\udd12 Long-Term Lock",
          "Repetition Effort": "5\u201310%",
          "Session ID": "19b421ce",
          "Session Date": "31/10/2025",
          "Subject Name": "Social",
          "Subject ID": "SUB227",
          "Topics Covered": "Decimal forms, Decimal places, Decimal fraction",
          "File Name(s)": "Decimal fraction, Decimal fraction",
          "File Link(s)": "https://drive.google.com/open?id=15eberZOt6dg4JDBASu9dnwin44hLYTCQ, https://drive.google.com/open?id=15eberZOt6dg4JDBASu9dnwin44hLYTCQ"
      },
      {
          "Curve ID": "CUR131",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "01/11/2025",
          "Repetition No.": 1,
          "Repetition Name": "\ud83e\udde0 Learn Concept",
          "Repetition Effort": "100%",
          "Session ID": "22c29cf5",
          "Session Date": "01/11/2025",
          "Subject Name": "MATHS",
          "Subject ID": "SUB227",
          "Topics Covered": "Decimal forms",
          "File Name(s)": "",
          "File Link(s)": ""
      },
      {
          "Curve ID": "CUR132",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "02/11/2025",
          "Repetition No.": 2,
          "Repetition Name": "\ud83d\udd01 Active Recall",
          "Repetition Effort": "60\u201370%",
          "Session ID": "22c29cf5",
          "Session Date": "01/11/2025",
          "Subject Name": "MATHS",
          "Subject ID": "SUB227",
          "Topics Covered": "Decimal forms",
          "File Name(s)": "",
          "File Link(s)": ""
      },
      {
          "Curve ID": "CUR133",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "04/11/2025",
          "Repetition No.": 3,
          "Repetition Name": "\ud83e\udde9 Fix Gaps",
          "Repetition Effort": "40\u201350%",
          "Session ID": "22c29cf5",
          "Session Date": "01/11/2025",
          "Subject Name": "MATHS",
          "Subject ID": "SUB227",
          "Topics Covered": "Decimal forms",
          "File Name(s)": "",
          "File Link(s)": ""
      },
      {
          "Curve ID": "CUR134",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "08/11/2025",
          "Repetition No.": 4,
          "Repetition Name": "\u26a1 Quick Review",
          "Repetition Effort": "20\u201330%",
          "Session ID": "22c29cf5",
          "Session Date": "01/11/2025",
          "Subject Name": "Social",
          "Subject ID": "SUB227",
          "Topics Covered": "Decimal forms",
          "File Name(s)": "",
          "File Link(s)": ""
      },
      {
          "Curve ID": "CUR135",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "15/11/2025",
          "Repetition No.": 5,
          "Repetition Name": "\ud83c\udfaf Final Boost",
          "Repetition Effort": "10\u201315%",
          "Session ID": "22c29cf5",
          "Session Date": "01/11/2025",
          "Subject Name": "Social",
          "Subject ID": "SUB227",
          "Topics Covered": "Decimal forms",
          "File Name(s)": "",
          "File Link(s)": ""
      },
      {
          "Curve ID": "CUR136",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "01/12/2025",
          "Repetition No.": 6,
          "Repetition Name": "\ud83d\udd12 Long-Term Lock",
          "Repetition Effort": "5\u201310%",
          "Session ID": "22c29cf5",
          "Session Date": "01/11/2025",
          "Subject Name": "MATHS",
          "Subject ID": "SUB227",
          "Topics Covered": "Decimal forms",
          "File Name(s)": "",
          "File Link(s)": ""
      },
      {
          "Curve ID": "CUR143",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "30/10/2025",
          "Repetition No.": 1,
          "Repetition Name": "\ud83e\udde0 Learn Concept",
          "Repetition Effort": "100%",
          "Session ID": "d3a55669",
          "Session Date": "30/10/2025",
          "Subject Name": "Social",
          "Subject ID": "SUB227",
          "Topics Covered": "Some other sums, Rivision of the chapter, Removing parts, (Chapter completed)",
          "File Name(s)": "Joining parts, Joining parts",
          "File Link(s)": "https://drive.google.com/open?id=1rRlLrJ-WMTt57nsmyO_wqKX6FReQlL7n, https://drive.google.com/open?id=1rRlLrJ-WMTt57nsmyO_wqKX6FReQlL7n"
      },
      {
          "Curve ID": "CUR144",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "31/10/2025",
          "Repetition No.": 2,
          "Repetition Name": "\ud83d\udd01 Active Recall",
          "Repetition Effort": "60\u201370%",
          "Session ID": "d3a55669",
          "Session Date": "30/10/2025",
          "Subject Name": "MATHS",
          "Subject ID": "SUB227",
          "Topics Covered": "Some other sums, Rivision of the chapter, Removing parts, (Chapter completed)",
          "File Name(s)": "Joining parts, Joining parts",
          "File Link(s)": "https://drive.google.com/open?id=1rRlLrJ-WMTt57nsmyO_wqKX6FReQlL7n, https://drive.google.com/open?id=1rRlLrJ-WMTt57nsmyO_wqKX6FReQlL7n"
      },
      {
          "Curve ID": "CUR145",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "02/11/2025",
          "Repetition No.": 3,
          "Repetition Name": "\ud83e\udde9 Fix Gaps",
          "Repetition Effort": "40\u201350%",
          "Session ID": "d3a55669",
          "Session Date": "30/10/2025",
          "Subject Name": "Social",
          "Subject ID": "SUB227",
          "Topics Covered": "Some other sums, Rivision of the chapter, Removing parts, (Chapter completed)",
          "File Name(s)": "Joining parts, Joining parts",
          "File Link(s)": "https://drive.google.com/open?id=1rRlLrJ-WMTt57nsmyO_wqKX6FReQlL7n, https://drive.google.com/open?id=1rRlLrJ-WMTt57nsmyO_wqKX6FReQlL7n"
      },
      {
          "Curve ID": "CUR146",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "06/11/2025",
          "Repetition No.": 4,
          "Repetition Name": "\u26a1 Quick Review",
          "Repetition Effort": "20\u201330%",
          "Session ID": "d3a55669",
          "Session Date": "30/10/2025",
          "Subject Name": "Social",
          "Subject ID": "SUB227",
          "Topics Covered": "Some other sums, Rivision of the chapter, Removing parts, (Chapter completed)",
          "File Name(s)": "Joining parts, Joining parts",
          "File Link(s)": "https://drive.google.com/open?id=1rRlLrJ-WMTt57nsmyO_wqKX6FReQlL7n, https://drive.google.com/open?id=1rRlLrJ-WMTt57nsmyO_wqKX6FReQlL7n"
      },
      {
          "Curve ID": "CUR147",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "13/11/2025",
          "Repetition No.": 5,
          "Repetition Name": "\ud83c\udfaf Final Boost",
          "Repetition Effort": "10\u201315%",
          "Session ID": "d3a55669",
          "Session Date": "30/10/2025",
          "Subject Name": "Social",
          "Subject ID": "SUB227",
          "Topics Covered": "Some other sums, Rivision of the chapter, Removing parts, (Chapter completed)",
          "File Name(s)": "Joining parts, Joining parts",
          "File Link(s)": "https://drive.google.com/open?id=1rRlLrJ-WMTt57nsmyO_wqKX6FReQlL7n, https://drive.google.com/open?id=1rRlLrJ-WMTt57nsmyO_wqKX6FReQlL7n"
      },
      {
          "Curve ID": "CUR148",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "29/11/2025",
          "Repetition No.": 6,
          "Repetition Name": "\ud83d\udd12 Long-Term Lock",
          "Repetition Effort": "5\u201310%",
          "Session ID": "d3a55669",
          "Session Date": "30/10/2025",
          "Subject Name": "MATHS",
          "Subject ID": "SUB227",
          "Topics Covered": "Some other sums, Rivision of the chapter, Removing parts, (Chapter completed)",
          "File Name(s)": "Joining parts, Joining parts",
          "File Link(s)": "https://drive.google.com/open?id=1rRlLrJ-WMTt57nsmyO_wqKX6FReQlL7n, https://drive.google.com/open?id=1rRlLrJ-WMTt57nsmyO_wqKX6FReQlL7n"
      },
      {
          "Curve ID": "CUR149",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "02/11/2025",
          "Repetition No.": 1,
          "Repetition Name": "\ud83e\udde0 Learn Concept",
          "Repetition Effort": "100%",
          "Session ID": "1c85cccb",
          "Session Date": "02/11/2025",
          "Subject Name": "MATHS",
          "Subject ID": "SUB227",
          "Topics Covered": "Decimal substraction ,Exam for Arithmetic forms",
          "File Name(s)": "Arithmetic of parts, Arithmetic of parts",
          "File Link(s)": "https://drive.google.com/open?id=1iQlPyJgSPWZyL_GMijAMAjCpUWw594FB, https://drive.google.com/open?id=1iQlPyJgSPWZyL_GMijAMAjCpUWw594FB"
      },
      {
          "Curve ID": "CUR150",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "03/11/2025",
          "Repetition No.": 2,
          "Repetition Name": "\ud83d\udd01 Active Recall",
          "Repetition Effort": "60\u201370%",
          "Session ID": "1c85cccb",
          "Session Date": "02/11/2025",
          "Subject Name": "Social",
          "Subject ID": "SUB227",
          "Topics Covered": "Decimal substraction ,Exam for Arithmetic forms",
          "File Name(s)": "Arithmetic of parts, Arithmetic of parts",
          "File Link(s)": "https://drive.google.com/open?id=1iQlPyJgSPWZyL_GMijAMAjCpUWw594FB, https://drive.google.com/open?id=1iQlPyJgSPWZyL_GMijAMAjCpUWw594FB"
      },
      {
          "Curve ID": "CUR151",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "05/11/2025",
          "Repetition No.": 3,
          "Repetition Name": "\ud83e\udde9 Fix Gaps",
          "Repetition Effort": "40\u201350%",
          "Session ID": "1c85cccb",
          "Session Date": "02/11/2025",
          "Subject Name": "MATHS",
          "Subject ID": "SUB227",
          "Topics Covered": "Decimal substraction ,Exam for Arithmetic forms",
          "File Name(s)": "Arithmetic of parts, Arithmetic of parts",
          "File Link(s)": "https://drive.google.com/open?id=1iQlPyJgSPWZyL_GMijAMAjCpUWw594FB, https://drive.google.com/open?id=1iQlPyJgSPWZyL_GMijAMAjCpUWw594FB"
      },
      {
          "Curve ID": "CUR152",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "09/11/2025",
          "Repetition No.": 4,
          "Repetition Name": "\u26a1 Quick Review",
          "Repetition Effort": "20\u201330%",
          "Session ID": "1c85cccb",
          "Session Date": "02/11/2025",
          "Subject Name": "MATHS",
          "Subject ID": "SUB227",
          "Topics Covered": "Decimal substraction ,Exam for Arithmetic forms",
          "File Name(s)": "Arithmetic of parts, Arithmetic of parts",
          "File Link(s)": "https://drive.google.com/open?id=1iQlPyJgSPWZyL_GMijAMAjCpUWw594FB, https://drive.google.com/open?id=1iQlPyJgSPWZyL_GMijAMAjCpUWw594FB"
      },
      {
          "Curve ID": "CUR153",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "16/11/2025",
          "Repetition No.": 5,
          "Repetition Name": "\ud83c\udfaf Final Boost",
          "Repetition Effort": "10\u201315%",
          "Session ID": "1c85cccb",
          "Session Date": "02/11/2025",
          "Subject Name": "Social",
          "Subject ID": "SUB227",
          "Topics Covered": "Decimal substraction ,Exam for Arithmetic forms",
          "File Name(s)": "Arithmetic of parts, Arithmetic of parts",
          "File Link(s)": "https://drive.google.com/open?id=1iQlPyJgSPWZyL_GMijAMAjCpUWw594FB, https://drive.google.com/open?id=1iQlPyJgSPWZyL_GMijAMAjCpUWw594FB"
      },
      {
          "Curve ID": "CUR154",
          "Student ID": "STD101",
          "Learned update": "",
          "Repetition Date": "02/12/2025",
          "Repetition No.": 6,
          "Repetition Name": "\ud83d\udd12 Long-Term Lock",
          "Repetition Effort": "5\u201310%",
          "Session ID": "1c85cccb",
          "Session Date": "02/11/2025",
          "Subject Name": "MATHS",
          "Subject ID": "SUB227",
          "Topics Covered": "Decimal substraction ,Exam for Arithmetic forms",
          "File Name(s)": "Arithmetic of parts, Arithmetic of parts",
          "File Link(s)": "https://drive.google.com/open?id=1iQlPyJgSPWZyL_GMijAMAjCpUWw594FB, https://drive.google.com/open?id=1iQlPyJgSPWZyL_GMijAMAjCpUWw594FB"
      }
  ],
  "STD102": [
      {
          "Curve ID": "CUR105",
          "Student ID": "STD102",
          "Learned update": "",
          "Repetition Date": "30/10/2025",
          "Repetition No.": 1,
          "Repetition Name": "\ud83e\udde0 Learn Concept",
          "Repetition Effort": "100%",
          "Session ID": "10bf442a",
          "Session Date": "30/10/2025",
          "Subject Name": "HINDI",
          "Subject ID": "SUB296",
          "Topics Covered": "7 th chap -Jan jan ka chehra ek",
          "File Name(s)": "",
          "File Link(s)": ""
      },
      {
          "Curve ID": "CUR110",
          "Student ID": "STD102",
          "Learned update": "",
          "Repetition Date": "31/10/2025",
          "Repetition No.": 2,
          "Repetition Name": "\ud83d\udd01 Active Recall",
          "Repetition Effort": "60\u201370%",
          "Session ID": "10bf442a",
          "Session Date": "30/10/2025",
          "Subject Name": "HINDI",
          "Subject ID": "SUB296",
          "Topics Covered": "7 th chap -Jan jan ka chehra ek",
          "File Name(s)": "",
          "File Link(s)": ""
      },
      {
          "Curve ID": "CUR115",
          "Student ID": "STD102",
          "Learned update": "",
          "Repetition Date": "02/11/2025",
          "Repetition No.": 3,
          "Repetition Name": "\ud83e\udde9 Fix Gaps",
          "Repetition Effort": "40\u201350%",
          "Session ID": "10bf442a",
          "Session Date": "30/10/2025",
          "Subject Name": "HINDI",
          "Subject ID": "SUB296",
          "Topics Covered": "7 th chap -Jan jan ka chehra ek",
          "File Name(s)": "",
          "File Link(s)": ""
      },
      {
          "Curve ID": "CUR120",
          "Student ID": "STD102",
          "Learned update": "",
          "Repetition Date": "6/11/2025",
          "Repetition No.": 4,
          "Repetition Name": "\u26a1 Quick Review",
          "Repetition Effort": "20\u201330%",
          "Session ID": "10bf442a",
          "Session Date": "30/10/2025",
          "Subject Name": "HINDI",
          "Subject ID": "SUB296",
          "Topics Covered": "7 th chap -Jan jan ka chehra ek",
          "File Name(s)": "",
          "File Link(s)": ""
      },
      {
          "Curve ID": "CUR125",
          "Student ID": "STD102",
          "Learned update": "",
          "Repetition Date": "13/11/2025",
          "Repetition No.": 5,
          "Repetition Name": "\ud83c\udfaf Final Boost",
          "Repetition Effort": "10\u201315%",
          "Session ID": "10bf442a",
          "Session Date": "30/10/2025",
          "Subject Name": "HINDI",
          "Subject ID": "SUB296",
          "Topics Covered": "7 th chap -Jan jan ka chehra ek",
          "File Name(s)": "",
          "File Link(s)": ""
      },
      {
          "Curve ID": "CUR130",
          "Student ID": "STD102",
          "Learned update": "",
          "Repetition Date": "29/11/2025",
          "Repetition No.": 6,
          "Repetition Name": "\ud83d\udd12 Long-Term Lock",
          "Repetition Effort": "5\u201310%",
          "Session ID": "10bf442a",
          "Session Date": "30/10/2025",
          "Subject Name": "HINDI",
          "Subject ID": "SUB296",
          "Topics Covered": "7 th chap -Jan jan ka chehra ek",
          "File Name(s)": "",
          "File Link(s)": ""
      },
      {
          "Curve ID": "CUR137",
          "Student ID": "STD102",
          "Learned update": "",
          "Repetition Date": "02/11/2025",
          "Repetition No.": 1,
          "Repetition Name": "\ud83e\udde0 Learn Concept",
          "Repetition Effort": "100%",
          "Session ID": "43aaf256",
          "Session Date": "02/11/2025",
          "Subject Name": "HINDI",
          "Subject ID": "SUB296",
          "Topics Covered": "Jan jan ka chehra ek",
          "File Name(s)": "Jan jan ka chehra ek, Jan jan ka chehra ek",
          "File Link(s)": "https://drive.google.com/open?id=1-8ikEYYVFWBG8WVZnM_SsCitX_63iwhE, https://drive.google.com/open?id=1-8ikEYYVFWBG8WVZnM_SsCitX_63iwhE"
      },
      {
          "Curve ID": "CUR138",
          "Student ID": "STD102",
          "Learned update": "",
          "Repetition Date": "03/11/2025",
          "Repetition No.": 2,
          "Repetition Name": "\ud83d\udd01 Active Recall",
          "Repetition Effort": "60\u201370%",
          "Session ID": "43aaf256",
          "Session Date": "02/11/2025",
          "Subject Name": "HINDI",
          "Subject ID": "SUB296",
          "Topics Covered": "Jan jan ka chehra ek",
          "File Name(s)": "Jan jan ka chehra ek, Jan jan ka chehra ek",
          "File Link(s)": "https://drive.google.com/open?id=1-8ikEYYVFWBG8WVZnM_SsCitX_63iwhE, https://drive.google.com/open?id=1-8ikEYYVFWBG8WVZnM_SsCitX_63iwhE"
      },
      {
          "Curve ID": "CUR139",
          "Student ID": "STD102",
          "Learned update": "",
          "Repetition Date": "05/11/2025",
          "Repetition No.": 3,
          "Repetition Name": "\ud83e\udde9 Fix Gaps",
          "Repetition Effort": "40\u201350%",
          "Session ID": "43aaf256",
          "Session Date": "02/11/2025",
          "Subject Name": "HINDI",
          "Subject ID": "SUB296",
          "Topics Covered": "Jan jan ka chehra ek",
          "File Name(s)": "Jan jan ka chehra ek, Jan jan ka chehra ek",
          "File Link(s)": "https://drive.google.com/open?id=1-8ikEYYVFWBG8WVZnM_SsCitX_63iwhE, https://drive.google.com/open?id=1-8ikEYYVFWBG8WVZnM_SsCitX_63iwhE"
      },
      {
          "Curve ID": "CUR140",
          "Student ID": "STD102",
          "Learned update": "",
          "Repetition Date": "09/11/2025",
          "Repetition No.": 4,
          "Repetition Name": "\u26a1 Quick Review",
          "Repetition Effort": "20\u201330%",
          "Session ID": "43aaf256",
          "Session Date": "02/11/2025",
          "Subject Name": "HINDI",
          "Subject ID": "SUB296",
          "Topics Covered": "Jan jan ka chehra ek",
          "File Name(s)": "Jan jan ka chehra ek, Jan jan ka chehra ek",
          "File Link(s)": "https://drive.google.com/open?id=1-8ikEYYVFWBG8WVZnM_SsCitX_63iwhE, https://drive.google.com/open?id=1-8ikEYYVFWBG8WVZnM_SsCitX_63iwhE"
      },
      {
          "Curve ID": "CUR141",
          "Student ID": "STD102",
          "Learned update": "",
          "Repetition Date": "16/11/2025",
          "Repetition No.": 5,
          "Repetition Name": "\ud83c\udfaf Final Boost",
          "Repetition Effort": "10\u201315%",
          "Session ID": "43aaf256",
          "Session Date": "02/11/2025",
          "Subject Name": "HINDI",
          "Subject ID": "SUB296",
          "Topics Covered": "Jan jan ka chehra ek",
          "File Name(s)": "Jan jan ka chehra ek, Jan jan ka chehra ek",
          "File Link(s)": "https://drive.google.com/open?id=1-8ikEYYVFWBG8WVZnM_SsCitX_63iwhE, https://drive.google.com/open?id=1-8ikEYYVFWBG8WVZnM_SsCitX_63iwhE"
      },
      {
          "Curve ID": "CUR142",
          "Student ID": "STD102",
          "Learned update": "",
          "Repetition Date": "02/12/2025",
          "Repetition No.": 6,
          "Repetition Name": "\ud83d\udd12 Long-Term Lock",
          "Repetition Effort": "5\u201310%",
          "Session ID": "43aaf256",
          "Session Date": "02/11/2025",
          "Subject Name": "HINDI",
          "Subject ID": "SUB296",
          "Topics Covered": "Jan jan ka chehra ek",
          "File Name(s)": "Jan jan ka chehra ek, Jan jan ka chehra ek",
          "File Link(s)": "https://drive.google.com/open?id=1-8ikEYYVFWBG8WVZnM_SsCitX_63iwhE, https://drive.google.com/open?id=1-8ikEYYVFWBG8WVZnM_SsCitX_63iwhE"
      },
      {
          "Curve ID": "CUR155",
          "Student ID": "STD102",
          "Learned update": "",
          "Repetition Date": "06/11/2025",
          "Repetition No.": 1,
          "Repetition Name": "\ud83e\udde0 Learn Concept",
          "Repetition Effort": "100%",
          "Session ID": "cceaf2aa",
          "Session Date": "06/11/2025",
          "Subject Name": "HINDI",
          "Subject ID": "SUB296",
          "Topics Covered": "Football ki dil ki raja",
          "File Name(s)": "Football ki dil ki raja, Football ki dil ki raja",
          "File Link(s)": "https://drive.google.com/open?id=1SrcIx2MuiB2Bk7ZMFMsALw4jCvWrI4i7, https://drive.google.com/open?id=1SrcIx2MuiB2Bk7ZMFMsALw4jCvWrI4i7"
      },
      {
          "Curve ID": "CUR156",
          "Student ID": "STD102",
          "Learned update": "",
          "Repetition Date": "07/11/2025",
          "Repetition No.": 2,
          "Repetition Name": "\ud83d\udd01 Active Recall",
          "Repetition Effort": "60\u201370%",
          "Session ID": "cceaf2aa",
          "Session Date": "06/11/2025",
          "Subject Name": "HINDI",
          "Subject ID": "SUB296",
          "Topics Covered": "Football ki dil ki raja",
          "File Name(s)": "Football ki dil ki raja, Football ki dil ki raja",
          "File Link(s)": "https://drive.google.com/open?id=1SrcIx2MuiB2Bk7ZMFMsALw4jCvWrI4i7, https://drive.google.com/open?id=1SrcIx2MuiB2Bk7ZMFMsALw4jCvWrI4i7"
      },
      {
          "Curve ID": "CUR157",
          "Student ID": "STD102",
          "Learned update": "",
          "Repetition Date": "09/11/2025",
          "Repetition No.": 3,
          "Repetition Name": "\ud83e\udde9 Fix Gaps",
          "Repetition Effort": "40\u201350%",
          "Session ID": "cceaf2aa",
          "Session Date": "06/11/2025",
          "Subject Name": "HINDI",
          "Subject ID": "SUB296",
          "Topics Covered": "Football ki dil ki raja",
          "File Name(s)": "Football ki dil ki raja, Football ki dil ki raja",
          "File Link(s)": "https://drive.google.com/open?id=1SrcIx2MuiB2Bk7ZMFMsALw4jCvWrI4i7, https://drive.google.com/open?id=1SrcIx2MuiB2Bk7ZMFMsALw4jCvWrI4i7"
      },
      {
          "Curve ID": "CUR158",
          "Student ID": "STD102",
          "Learned update": "",
          "Repetition Date": "13/11/2025",
          "Repetition No.": 4,
          "Repetition Name": "\u26a1 Quick Review",
          "Repetition Effort": "20\u201330%",
          "Session ID": "cceaf2aa",
          "Session Date": "06/11/2025",
          "Subject Name": "HINDI",
          "Subject ID": "SUB296",
          "Topics Covered": "Football ki dil ki raja",
          "File Name(s)": "Football ki dil ki raja, Football ki dil ki raja",
          "File Link(s)": "https://drive.google.com/open?id=1SrcIx2MuiB2Bk7ZMFMsALw4jCvWrI4i7, https://drive.google.com/open?id=1SrcIx2MuiB2Bk7ZMFMsALw4jCvWrI4i7"
      },
      {
          "Curve ID": "CUR159",
          "Student ID": "STD102",
          "Learned update": "",
          "Repetition Date": "20/11/2025",
          "Repetition No.": 5,
          "Repetition Name": "\ud83c\udfaf Final Boost",
          "Repetition Effort": "10\u201315%",
          "Session ID": "cceaf2aa",
          "Session Date": "06/11/2025",
          "Subject Name": "HINDI",
          "Subject ID": "SUB296",
          "Topics Covered": "Football ki dil ki raja",
          "File Name(s)": "Football ki dil ki raja, Football ki dil ki raja",
          "File Link(s)": "https://drive.google.com/open?id=1SrcIx2MuiB2Bk7ZMFMsALw4jCvWrI4i7, https://drive.google.com/open?id=1SrcIx2MuiB2Bk7ZMFMsALw4jCvWrI4i7"
      },
      {
          "Curve ID": "CUR160",
          "Student ID": "STD102",
          "Learned update": "",
          "Repetition Date": "06/12/2025",
          "Repetition No.": 6,
          "Repetition Name": "\ud83d\udd12 Long-Term Lock",
          "Repetition Effort": "5\u201310%",
          "Session ID": "cceaf2aa",
          "Session Date": "06/11/2025",
          "Subject Name": "HINDI",
          "Subject ID": "SUB296",
          "Topics Covered": "Football ki dil ki raja",
          "File Name(s)": "Football ki dil ki raja, Football ki dil ki raja",
          "File Link(s)": "https://drive.google.com/open?id=1SrcIx2MuiB2Bk7ZMFMsALw4jCvWrI4i7, https://drive.google.com/open?id=1SrcIx2MuiB2Bk7ZMFMsALw4jCvWrI4i7"
      }
  ]
}
